// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qlaeuezqhbhmyvueqdmq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsYWV1ZXpxaGJobXl2dWVxZG1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMTM1MjksImV4cCI6MjA2OTc4OTUyOX0.aQ3F6_XxQmnkHifO3_yNxbqrog3o7b5AW9Xl95_fNQg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});